export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const ADD_TODOTEXT = "ADD_TODOTEXT";
export const FETCH_TODO_ITEMS = "FETCH_TODO_ITEMS";
export const FETCH_TODO_ITEMS_SUCCESS = "FETCH_TODO_ITEMS_SUCCESS";
export const FETCH_TODO_ITEMS_FAID = "FETCH_TODO_ITEMS_FAID";